spring:
  datasource:
    #    driver-class-name: org.postgresql.Driver
    url: ENC(Ey8MQ2rt1L65Th4A2CVOFE8QCZJdYZ5RYfyaSCmiWKdDMqGWo4lcBJ9qoaAMdwAaRXMCsZ22Xj8=)
    username: ENC(5RxqVoOaLfkqh3FGRRRC/r6e+hkWJgtr)
    password: ENC(jaN0ffgCGXju6GtewSTa6hwEiPRchMnt9sk5Bw+WJao=)

cloud:
  aws:
    credentials:
      access-key: ENC(W2wrTDVaWIaUSAsPCY3LIgKi190lDZivG7gCzLW4gkY=)
      secret-key: ENC(RcC2O9GgXXxqeTNTjJccvdT96I9EMWOSnthGwWMCh4MTduXVySEYS9ohdYEh8dEBKiTf0q7cMl8=)
    s3:
      bucket: t-gather
    region:
      static: ap-northeast-2
    stack:
      auto: false

app:
  oauth2:
    kakao:
      client-id: ENC(r+HIOeO/MgDHo6gr2Kc4JnfXCL5YKPR1c5ZtEOvyQs9h4uQH4ZQ0rBoVG78DZ+hh)
      client-secret: SeiXyrqnE1MIbGzF7yiWdJefWib9C5Ji
      redirect-uri: ${app.api-host}/api/oauth2/callback/kakao
      profile-api-url: https://kapi.kakao.com/v2/user/me
      token-api-url: https://kauth.kakao.com/oauth/token
    naver:
      client-id: riRGjszZsqtrRvcOOEdT
      client-secret: FqSTEQ2QGt
      redirect-uri: ${app.api-host}/api/oauth2/callback/naver
      profile-api-url: https://openapi.naver.com/v1/nid/me
    google:
      client-id: ENC(LvRpUoJTLwFfA5Cwdmg/rcQ75VM77y7sFJ4qGORWrWsyG/WHOB9i5Yb0Il1lB9gtoznNvC8MbOhlp2Nddf3mZ8L5g9wqi/BboI7/VOgcoutZlz5ALxYBUg==)
      client-secret: ENC(uCLykUOO3EdQ1av9oyLtB5vy7AvXHUdUY0PlygbUjkIUJmg3Nbbr2KBdf4G2mkA/)
      redirect-uri: ${app.api-host}/api/oauth2/callback/google
      profile-api-url: https://www.googleapis.com/oauth2/v1/userinfo
      scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
