spring:
  datasource:
    #    driver-class-name: org.postgresql.Driver
    url: ENC(Ey8MQ2rt1L65Th4A2CVOFE8QCZJdYZ5RYfyaSCmiWKdDMqGWo4lcBJ9qoaAMdwAaRXMCsZ22Xj8=)
    username: ENC(5RxqVoOaLfkqh3FGRRRC/r6e+hkWJgtr)
    password: ENC(jaN0ffgCGXju6GtewSTa6hwEiPRchMnt9sk5Bw+WJao=)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(IdJ4GnQm+C5WfqXXKmKWF9slbYD5wh/TmmmDHS74nO0=)
    password: ENC(l5JF9Mh5ds3oYf6/sRNXySmGwmdqLdvHE1++gl28lRo=)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
cloud:
  aws:
    credentials:
      # access-key: ENC(E07zGZYYJL3jQR9cH6jBzirb6ZJRy8kL2e+bVuelrJg=)
      # access-key: ENC(Ja7+QsnMEimHGKmOYo4fBoMMb2WlH+qa2TL8n3eK018=)
      access-key: ENC(v6tTmANYePlNJcit5IncpBbBXQqWrIMEVXEUmXZYeDE=)
      # secret-key: ENC(k6ej1v44RB9mhZjmRQi6qyhJDWMNbQ7rwdOEn8H/UUs9XAK7cueiYXRBPkQbI7x0drloPTSzCgg=)
      # secret-key: ENC(oQAHVbxN9wzcFjDUfAV9aHoF3EhrMU39k7mvnARJKge50w9FMnv8pFqtMro6bywh7bsCB0aeo+o=)
      secret-key: ENC(fHUHpAb9Po8oC10xNjtliBzAX4CQdlc8yOFXbz+WZ/kJVOuWRaDV2oURtfOtr8zeKsJl+CeMD8A=)
    s3:
      bucket: t-gather
    region:
      static: ap-northeast-2
    stack:
      auto: false

app:
  oauth2:
    kakao:
      client-id: ENC(r+HIOeO/MgDHo6gr2Kc4JnfXCL5YKPR1c5ZtEOvyQs9h4uQH4ZQ0rBoVG78DZ+hh)
      client-secret: SeiXyrqnE1MIbGzF7yiWdJefWib9C5Ji
      redirect-uri: ${app.api-host}/api/oauth2/callback/kakao
      profile-api-url: https://kapi.kakao.com/v2/user/me
      token-api-url: https://kauth.kakao.com/oauth/token
    naver:
      client-id: riRGjszZsqtrRvcOOEdT
      client-secret: FqSTEQ2QGt
      redirect-uri: ${app.api-host}/api/oauth2/callback/naver
      profile-api-url: https://openapi.naver.com/v1/nid/me
    google:
      client-id: ENC(LvRpUoJTLwFfA5Cwdmg/rcQ75VM77y7sFJ4qGORWrWsyG/WHOB9i5Yb0Il1lB9gtoznNvC8MbOhlp2Nddf3mZ8L5g9wqi/BboI7/VOgcoutZlz5ALxYBUg==)
      client-secret: ENC(uCLykUOO3EdQ1av9oyLtB5vy7AvXHUdUY0PlygbUjkIUJmg3Nbbr2KBdf4G2mkA/)
      redirect-uri: ${app.api-host}/api/oauth2/callback/google
      profile-api-url: https://www.googleapis.com/oauth2/v1/userinfo
      scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
